import type { LessonWithParticipants } from '@/services/scheduling/lessons.service';
import type { DayOfWeek } from '@/lib/types';

/** One candidate lesson+destination pair generated by candidateGenerator.ts (Steps 1-2). */
export interface MoveCandidate {
  lesson: LessonWithParticipants;
  teacherId: string;
  teacherName: string;
  dayOfWeek: DayOfWeek;
  fromStartMinute: number;
  toStartMinute: number;
  durationMinutes: number;
  fromInPrimeTime: boolean;
  toInPrimeTime: boolean;
  preservationBeforeScore: number;
  /** Honest prediction reusing get_teacher_preservation_score's own formula: teacher/day components are
   * unchanged by a same-teacher same-day move, but time_component always resets to 0 the instant the
   * time actually changes (same_time_since becomes today) — this can be zero or negative, never assumed positive. */
  preservationAfterScore: number;
  /** This candidate's own teacher's weekly lesson count — kept per-candidate (not read from a single
   * global "busiest teacher") since candidates can now come from any teacher in the overloaded pool. */
  teacherWeeklyLessons: number;
}

/** One scoring rule's verdict for a single candidate. Reasons are structured (i18n key + params),
 * never pre-rendered English strings, so "Why" renders correctly in whichever language is active. */
export interface ScoredFactor {
  id: string;
  priority: number;
  points: number;
  labelCode: string;
  labelParams?: Record<string, string | number>;
  detailCode: string;
  detailParams?: Record<string, string | number>;
}

/** A pluggable scoring rule. Add/remove/reorder rules here without touching the generator or UI. */
export interface ScoringRule {
  id: string;
  priority: number; // 1 = highest priority, per spec order
  evaluate: (candidate: MoveCandidate) => Omit<ScoredFactor, 'id' | 'priority'>;
}

export interface ScoredCandidate {
  candidate: MoveCandidate;
  totalScore: number;
  maxPossibleScore: number;
  confidencePct: number;
  factors: ScoredFactor[];
  /** Real Operations Score point gain this move would produce (same weight the score engine itself uses). */
  operationsScoreGain: number;
}
